/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#151310',
        'surface-dim': '#151310',
        'surface-bright': '#3c3935',
        'surface-container-lowest': '#100e0b',
        'surface-container-low': '#1e1b18',
        'surface-container': '#221f1c',
        'surface-container-high': '#2d2926',
        'surface-container-highest': '#383431',
        'on-surface': '#e8e1dc',
        'on-surface-variant': '#d1c5b7',
        'inverse-surface': '#e8e1dc',
        'inverse-on-surface': '#33302c',
        outline: '#9a8f83',
        'outline-variant': '#4e453b',
        'surface-tint': '#e2c195',
        primary: '#e5c497',
        'on-primary': '#402d0c',
        'primary-container': '#c8a97e',
        'on-primary-container': '#533e1c',
        'inverse-primary': '#735a36',
        'primary-fixed': '#ffddb0',
        'primary-fixed-dim': '#e2c195',
        'on-primary-fixed': '#281800',
        'on-primary-fixed-variant': '#594320',
        secondary: '#c8c5d0',
        'on-secondary': '#303038',
        'secondary-container': '#494851',
        'on-secondary-container': '#b9b7c1',
        tertiary: '#bacae6',
        'on-tertiary': '#213147',
        'tertiary-container': '#9fafca',
        'on-tertiary-container': '#334259',
        'surface-variant': '#383431',
        background: '#151310',
        'on-background': '#e8e1dc',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'border-interaction': '#3d3d50',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-path': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      spacing: {
        'sidebar-width': '220px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'card-gap': '12px',
      },
      borderRadius: {
        card: '0.75rem',
        btn: '0.5rem',
      },
      boxShadow: {
        card: '0 8px 30px rgb(0 0 0 / 0.4)',
        elevated: '0 4px 24px rgb(0 0 0 / 0.35)',
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
